# Generated by Django 4.2.3 on 2023-08-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendico', '0005_productcategory_productimage_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_URL',
        ),
    ]
