# Generated by Django 4.2.3 on 2023-08-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trendico', '0008_userreview_topsellingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='stock_events', to='trendico.eventtype'),
        ),
    ]
